-- PM Konstruct v2 -- baseline schema
--
-- Generated by tools/phase3/gen_baseline.py from the legacy production
-- schema (database-backups/development/schema.sql), then verified byte-
-- equivalent by tools/phase3/verify_baseline.sh. Do not hand-edit: change
-- the generator, or add a later migration.
--
-- Deliberately excluded legacy tables:
--   _schema_version           -> replaced by sqlx migration tracking
--   supabase_import_mappings  -> artefact of the previous Supabase migration
--
-- 38 tables, in foreign-key dependency order.
--
-- Orphaned legacy functions NOT carried over (no trigger references either,
-- and the `_updated_at` column set_updated_at() targets does not exist):
--   set_updated_at, set_updated_at_metadata

-- ==========================================================================
-- Extensions
-- ==========================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- --------------------------------------------------------------------------
CREATE TABLE ai_usage_daily (
  id                         serial NOT NULL,
  user_id                    integer NOT NULL,
  date                       text NOT NULL,
  request_count              integer NOT NULL DEFAULT 0,
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_usage_daily_pkey PRIMARY KEY (id),
  CONSTRAINT ai_usage_daily_user_id_date_unique UNIQUE (user_id, date)
);

-- --------------------------------------------------------------------------
CREATE TABLE billing_webhook_notifications (
  stripe_event_id            text NOT NULL,
  event_type                 text NOT NULL,
  status                     text NOT NULL DEFAULT 'pending'::text,
  last_error                 text,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  delivered_at               timestamp with time zone,
  CONSTRAINT billing_webhook_notifications_pkey PRIMARY KEY (stripe_event_id),
  CONSTRAINT billing_webhook_notifications_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'delivered'::text, 'failed'::text])))
);

-- --------------------------------------------------------------------------
CREATE TABLE billing_webhook_notification_recipients (
  id                         bigserial NOT NULL,
  stripe_event_id            text NOT NULL,
  recipient_email            text NOT NULL,
  recipient_name             text NOT NULL,
  company_name               text NOT NULL,
  email_kind                 text NOT NULL,
  trial_ends_at              timestamp with time zone,
  status                     text NOT NULL DEFAULT 'pending'::text,
  attempt_count              integer NOT NULL DEFAULT 0,
  next_attempt_at            timestamp with time zone,
  last_attempt_at            timestamp with time zone,
  delivered_at               timestamp with time zone,
  last_error                 text,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  operator_alerted_at        timestamp with time zone,
  claim_token                text,
  claim_expires_at           timestamp with time zone,
  ambiguous_since            timestamp with time zone,
  CONSTRAINT billing_webhook_notification_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT billing_webhook_notification__stripe_event_id_recipient_ema_key UNIQUE (stripe_event_id, recipient_email),
  CONSTRAINT billing_webhook_notification_recipients_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'delivered'::text, 'failed'::text, 'review'::text])))
);
CREATE INDEX billing_webhook_recipient_retry_due_idx ON public.billing_webhook_notification_recipients USING btree (next_attempt_at, id) WHERE (status = ANY (ARRAY['pending'::text, 'failed'::text, 'processing'::text]));

-- --------------------------------------------------------------------------
CREATE TABLE companies (
  id                         serial NOT NULL,
  name                       text NOT NULL,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  stripe_customer_id         text,
  stripe_subscription_id     text,
  billing_price_id           text,
  billing_plan_key           text,
  billing_seat_quantity      integer,
  billing_trial_ends_at      timestamp without time zone,
  billing_onboarding_completed boolean NOT NULL DEFAULT true,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE users (
  id                         serial NOT NULL,
  name                       text NOT NULL,
  email                      text NOT NULL,
  role                       text NOT NULL DEFAULT 'SUPERVISOR'::text,
  phone                      text,
  active                     boolean NOT NULL DEFAULT true,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  password_hash              text,
  company_id                 integer NOT NULL,
  password_changed_at        timestamp without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_unique UNIQUE (email)
);

-- --------------------------------------------------------------------------
CREATE TABLE jobs (
  id                         serial NOT NULL,
  name                       text NOT NULL,
  job_number                 text NOT NULL,
  client                     text NOT NULL,
  address                    text NOT NULL,
  status                     text NOT NULL DEFAULT 'active'::text,
  start_date                 date,
  end_date                   date,
  description                text,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  client_number              text,
  manager_id                 integer,
  supervisor_id              integer,
  dropbox_path               text,
  company_id                 integer NOT NULL,
  client_email               text,
  contact2_name              text,
  contact2_phone             text,
  contact2_email             text,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_company_job_number_unique UNIQUE (company_id, job_number)
);

-- --------------------------------------------------------------------------
CREATE TABLE call_forward (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  title                      text NOT NULL,
  item_type                  character varying(20) NOT NULL DEFAULT 'TASK'::character varying,
  supplier_trade             character varying(150),
  est_start                  date,
  est_finish                 date,
  actual_start               date,
  actual_finish              date,
  status                     character varying(30) NOT NULL DEFAULT 'not_started'::character varying,
  notes                      text,
  sort_order                 integer NOT NULL DEFAULT 0,
  parent_id                  integer,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT call_forward_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE call_forward_templates (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  name                       text NOT NULL,
  description                text,
  items                      jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT call_forward_templates_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE company_branding (
  id                         serial NOT NULL,
  company_name               text NOT NULL DEFAULT 'PM Konstruct'::text,
  logo_url                   text,
  primary_color              text NOT NULL DEFAULT '#E84E1B'::text,
  sidebar_color              text NOT NULL DEFAULT '#0f1117'::text,
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  company_id                 integer NOT NULL,
  banner_url                 text,
  job_display_mode           text NOT NULL DEFAULT 'job_number'::text,
  email_send_mode            text NOT NULL DEFAULT 'device'::text,
  CONSTRAINT company_branding_pkey PRIMARY KEY (id),
  CONSTRAINT company_branding_company_id_unique UNIQUE (company_id)
);

-- --------------------------------------------------------------------------
CREATE TABLE site_diary (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  date                       date NOT NULL,
  weather                    text,
  workforce                  integer,
  work_completed             text NOT NULL,
  materials                  text,
  equipment                  text,
  visitors                   text,
  issues                     text,
  notes                      text,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  time                       text,
  author_id                  integer,
  trades_on_site             text,
  safety_notes               text,
  client_instructions        text,
  location_name              text,
  location_lat               numeric(9,6),
  location_lng               numeric(9,6),
  temperature                numeric(5,1),
  weather_condition          text,
  weather_icon               text,
  wind_speed_kmh             numeric(6,1),
  rainfall_mm                numeric(6,1),
  sunrise_time               text,
  sunset_time                text,
  action_status              text,
  action_raised_by           integer,
  CONSTRAINT site_diary_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE diary_notes (
  id                         serial NOT NULL,
  diary_entry_id             integer NOT NULL,
  category                   text NOT NULL DEFAULT 'general'::text,
  content                    text NOT NULL,
  action_status              text,
  action_raised_by           integer,
  sort_order                 integer NOT NULL DEFAULT 0,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  archived                   boolean NOT NULL DEFAULT false,
  CONSTRAINT diary_notes_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE diary_media (
  id                         serial NOT NULL,
  diary_entry_id             integer NOT NULL,
  file_type                  character varying(10) NOT NULL,
  mime_type                  character varying(100) NOT NULL,
  original_name              character varying(255) NOT NULL,
  stored_name                character varying(255) NOT NULL,
  file_size                  integer NOT NULL,
  url                        character varying(500) NOT NULL,
  uploaded_by                integer,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  note_id                    integer,
  CONSTRAINT diary_media_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE diary_note_comments (
  id                         serial NOT NULL,
  note_id                    integer NOT NULL,
  author_id                  integer,
  content                    text NOT NULL,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT diary_note_comments_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE email_settings (
  id                         serial NOT NULL,
  smtp_host                  text,
  smtp_port                  integer DEFAULT 587,
  smtp_user                  text,
  smtp_pass                  text,
  smtp_from                  text,
  smtp_secure                boolean DEFAULT false,
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  company_id                 integer NOT NULL,
  CONSTRAINT email_settings_pkey PRIMARY KEY (id),
  CONSTRAINT email_settings_company_id_unique UNIQUE (company_id)
);

-- --------------------------------------------------------------------------
CREATE TABLE eto_job_sequences (
  job_id                     integer NOT NULL,
  next_number                integer NOT NULL DEFAULT 1,
  CONSTRAINT eto_job_sequences_pkey PRIMARY KEY (job_id),
  CONSTRAINT eto_job_sequences_next_number_check CHECK ((next_number > 0))
);

-- --------------------------------------------------------------------------
CREATE TABLE inspection_forms (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  job_id                     integer NOT NULL,
  created_by                 integer NOT NULL,
  diary_entry_id             integer NOT NULL,
  diary_note_id              integer NOT NULL,
  inspection_date            date NOT NULL,
  inspector                  text NOT NULL DEFAULT ''::text,
  inspection_type            text NOT NULL DEFAULT ''::text,
  stage                      text NOT NULL DEFAULT ''::text,
  observations               text NOT NULL DEFAULT ''::text,
  weather_data               jsonb,
  revision                   integer NOT NULL DEFAULT 0,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inspection_forms_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_forms_user_job_unique UNIQUE (company_id, job_id, created_by)
);

-- --------------------------------------------------------------------------
CREATE TABLE inspection_form_items (
  id                         serial NOT NULL,
  form_id                    integer NOT NULL,
  client_key                 character varying(100) NOT NULL,
  room                       text NOT NULL DEFAULT ''::text,
  description                text NOT NULL DEFAULT ''::text,
  actioned                   boolean NOT NULL DEFAULT false,
  sort_order                 integer NOT NULL DEFAULT 0,
  CONSTRAINT inspection_form_items_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_form_items_client_key_unique UNIQUE (form_id, client_key)
);
CREATE INDEX idx_inspection_form_items_form ON public.inspection_form_items USING btree (form_id, sort_order);

-- --------------------------------------------------------------------------
CREATE TABLE inspection_form_media (
  id                         serial NOT NULL,
  form_id                    integer NOT NULL,
  item_id                    integer NOT NULL,
  diary_media_id             integer NOT NULL,
  sort_order                 integer NOT NULL DEFAULT 0,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inspection_form_media_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_inspection_form_media_form ON public.inspection_form_media USING btree (form_id, item_id, sort_order);

-- --------------------------------------------------------------------------
CREATE TABLE job_assignments (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  user_id                    integer NOT NULL,
  is_primary                 boolean NOT NULL DEFAULT false,
  assigned_at                timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_assignments_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE job_dropbox_folders (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  company_id                 integer NOT NULL,
  label                      text NOT NULL DEFAULT 'Dropbox Files'::text,
  path                       text NOT NULL,
  sort_order                 integer NOT NULL DEFAULT 0,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_dropbox_folders_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE job_dropbox_auto_uploads (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  company_id                 integer NOT NULL,
  folder_id                  integer NOT NULL,
  enabled                    boolean NOT NULL DEFAULT true,
  last_run_date              date,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  frequency                  character varying(10) NOT NULL DEFAULT 'daily'::character varying,
  last_run_at                timestamp with time zone,
  run_claimed_at             timestamp with time zone,
  CONSTRAINT job_dropbox_auto_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT job_dropbox_auto_uploads_job_id_key UNIQUE (job_id)
);

-- --------------------------------------------------------------------------
CREATE TABLE job_dropbox_uploads (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  company_id                 integer NOT NULL,
  folder_id                  integer NOT NULL,
  media_source               character varying(12) NOT NULL,
  media_id                   integer NOT NULL,
  dropbox_path               text,
  status                     character varying(12) NOT NULL DEFAULT 'pending'::character varying,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  completed_at               timestamp with time zone,
  CONSTRAINT job_dropbox_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT uq_job_dropbox_upload_media UNIQUE (job_id, folder_id, media_source, media_id)
);

-- --------------------------------------------------------------------------
CREATE TABLE job_media (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  file_type                  character varying(10) NOT NULL DEFAULT 'photo'::character varying,
  mime_type                  character varying(100) NOT NULL,
  original_name              character varying(255) NOT NULL,
  stored_name                character varying(255) NOT NULL,
  file_size                  integer NOT NULL,
  url                        character varying(500) NOT NULL,
  source                     character varying(30) NOT NULL DEFAULT 'upload'::character varying,
  source_path                text,
  uploaded_by                integer,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_media_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_job_media_job_created ON public.job_media USING btree (job_id, created_at DESC);

-- --------------------------------------------------------------------------
CREATE TABLE job_tasks (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  title                      text NOT NULL,
  status                     text NOT NULL DEFAULT 'pending'::text,
  notes                      text,
  sort_order                 integer NOT NULL DEFAULT 0,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT job_tasks_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE media_deletion_queue (
  id                         serial NOT NULL,
  stored_name                character varying(255) NOT NULL,
  attempts                   integer NOT NULL DEFAULT 0,
  last_error                 text,
  last_attempt_at            timestamp with time zone,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT media_deletion_queue_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uq_media_deletion_queue_stored_name ON public.media_deletion_queue USING btree (stored_name);

-- --------------------------------------------------------------------------
CREATE TABLE notifications (
  id                         serial NOT NULL,
  user_id                    integer NOT NULL,
  type                       character varying(60) NOT NULL,
  title                      text NOT NULL,
  body                       text,
  link                       text,
  read_at                    timestamp without time zone,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  resolved_at                timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_notifications_backup_warning ON public.notifications USING btree (user_id, type, link, created_at) WHERE (resolved_at IS NULL);

-- --------------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
  id                         serial NOT NULL,
  user_id                    integer NOT NULL,
  token                      text NOT NULL,
  expires_at                 timestamp with time zone NOT NULL,
  used_at                    timestamp with time zone,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_tokens_token_unique UNIQUE (token)
);

-- --------------------------------------------------------------------------
CREATE TABLE progress (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  date                       date NOT NULL,
  percent_complete           real NOT NULL,
  milestone                  text,
  description                text,
  photos                     text[],
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT progress_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE push_subscriptions (
  id                         serial NOT NULL,
  user_id                    integer NOT NULL,
  endpoint                   text NOT NULL,
  p256dh                     text NOT NULL,
  auth                       text NOT NULL,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint)
);

-- --------------------------------------------------------------------------
CREATE TABLE reports (
  id                         serial NOT NULL,
  job_id                     integer NOT NULL,
  title                      text NOT NULL,
  type                       text NOT NULL,
  content                    text NOT NULL,
  generated_at               timestamp without time zone NOT NULL DEFAULT now(),
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT reports_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE scheduler_maintenance_jobs (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  name                       text NOT NULL,
  reference                  text,
  address                    text,
  status                     text NOT NULL DEFAULT 'active'::text,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scheduler_maintenance_jobs_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE scheduler_workers (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  name                       text NOT NULL,
  trade                      text,
  color                      text NOT NULL DEFAULT '#3B82F6'::text,
  active                     boolean NOT NULL DEFAULT true,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  on_leave                   boolean NOT NULL DEFAULT false,
  leave_from                 date,
  leave_to                   date,
  CONSTRAINT scheduler_workers_pkey PRIMARY KEY (id)
);

-- --------------------------------------------------------------------------
CREATE TABLE scheduler_allocations (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  worker_id                  integer NOT NULL,
  job_id                     integer,
  assigned_date              date NOT NULL,
  note                       text,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  maintenance_job_id         integer,
  CONSTRAINT scheduler_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT uq_scheduler_company_worker_date UNIQUE (company_id, worker_id, assigned_date),
  CONSTRAINT uq_scheduler_worker_job_date UNIQUE (worker_id, job_id, assigned_date),
  CONSTRAINT scheduler_allocation_target_check CHECK ((((job_id IS NOT NULL) AND (maintenance_job_id IS NULL)) OR ((job_id IS NULL) AND (maintenance_job_id IS NOT NULL))))
);
CREATE INDEX idx_scheduler_allocations_company_date ON public.scheduler_allocations USING btree (company_id, assigned_date);
CREATE UNIQUE INDEX uq_scheduler_worker_maintenance_job_date ON public.scheduler_allocations USING btree (worker_id, maintenance_job_id, assigned_date) WHERE (maintenance_job_id IS NOT NULL);

-- --------------------------------------------------------------------------
CREATE TABLE scheduler_job_day_notes (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  job_id                     integer NOT NULL,
  note_date                  date NOT NULL,
  note                       text NOT NULL,
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT scheduler_job_day_notes_pkey PRIMARY KEY (id),
  CONSTRAINT uq_scheduler_job_day_note UNIQUE (job_id, note_date)
);

-- --------------------------------------------------------------------------
CREATE TABLE scheduler_worker_absences (
  id                         serial NOT NULL,
  company_id                 integer NOT NULL,
  worker_id                  integer NOT NULL,
  absence_type               text NOT NULL,
  start_date                 date NOT NULL,
  end_date                   date NOT NULL,
  created_at                 timestamp with time zone NOT NULL DEFAULT now(),
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scheduler_worker_absences_pkey PRIMARY KEY (id),
  CONSTRAINT uq_scheduler_worker_absence_period UNIQUE (worker_id, absence_type, start_date, end_date),
  CONSTRAINT scheduler_worker_absence_dates_check CHECK ((start_date <= end_date)),
  CONSTRAINT scheduler_worker_absence_type_check CHECK ((absence_type = ANY (ARRAY['sick'::text, 'leave'::text, 'trade_school'::text])))
);
CREATE INDEX idx_scheduler_worker_absences_company_dates ON public.scheduler_worker_absences USING btree (company_id, start_date, end_date);
CREATE INDEX idx_scheduler_worker_absences_worker_dates ON public.scheduler_worker_absences USING btree (worker_id, start_date, end_date);

-- --------------------------------------------------------------------------
CREATE TABLE user_notification_prefs (
  id                         serial NOT NULL,
  user_id                    integer NOT NULL,
  notify_action_notes        boolean NOT NULL DEFAULT true,
  notify_call_forward        boolean NOT NULL DEFAULT false,
  updated_at                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_notification_prefs_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_prefs_user_id_key UNIQUE (user_id)
);

-- --------------------------------------------------------------------------
CREATE TABLE user_permissions (
  id                         serial NOT NULL,
  user_id                    integer NOT NULL,
  resource                   character varying(100) NOT NULL,
  action                     character varying(100) NOT NULL,
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_id_resource_action_unique UNIQUE (user_id, resource, action)
);

-- --------------------------------------------------------------------------
CREATE TABLE weather_snapshots (
  id                         serial NOT NULL,
  diary_entry_id             integer NOT NULL,
  temperature_c              numeric(5,1),
  conditions                 character varying(100),
  rain                       character varying(20) DEFAULT 'none'::character varying,
  wind_description           character varying(100),
  wind_speed_kmh             numeric(5,1),
  humidity_pct               integer,
  source                     character varying(20) NOT NULL DEFAULT 'manual'::character varying,
  snapshot_at                timestamp without time zone NOT NULL DEFAULT now(),
  created_at                 timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT weather_snapshots_pkey PRIMARY KEY (id)
);


-- ==========================================================================
-- Foreign keys, applied after all tables exist.
-- ==========================================================================

ALTER TABLE billing_webhook_notification_recipients ADD CONSTRAINT billing_webhook_notification_recipients_stripe_event_id_fkey FOREIGN KEY (stripe_event_id) REFERENCES billing_webhook_notifications(stripe_event_id) ON DELETE CASCADE;
ALTER TABLE call_forward ADD CONSTRAINT call_forward_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE call_forward_templates ADD CONSTRAINT call_forward_templates_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE company_branding ADD CONSTRAINT company_branding_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE diary_media ADD CONSTRAINT diary_media_diary_entry_id_site_diary_id_fk FOREIGN KEY (diary_entry_id) REFERENCES site_diary(id) ON DELETE CASCADE;
ALTER TABLE diary_media ADD CONSTRAINT diary_media_note_id_diary_notes_id_fk FOREIGN KEY (note_id) REFERENCES diary_notes(id) ON DELETE CASCADE;
ALTER TABLE diary_media ADD CONSTRAINT diary_media_uploaded_by_users_id_fk FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE diary_note_comments ADD CONSTRAINT diary_note_comments_author_id_users_id_fk FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE diary_note_comments ADD CONSTRAINT diary_note_comments_note_id_diary_notes_id_fk FOREIGN KEY (note_id) REFERENCES diary_notes(id) ON DELETE CASCADE;
ALTER TABLE diary_notes ADD CONSTRAINT diary_notes_action_raised_by_users_id_fk FOREIGN KEY (action_raised_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE diary_notes ADD CONSTRAINT diary_notes_diary_entry_id_site_diary_id_fk FOREIGN KEY (diary_entry_id) REFERENCES site_diary(id) ON DELETE CASCADE;
ALTER TABLE email_settings ADD CONSTRAINT email_settings_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE eto_job_sequences ADD CONSTRAINT eto_job_sequences_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE inspection_form_items ADD CONSTRAINT inspection_form_items_form_id_fkey FOREIGN KEY (form_id) REFERENCES inspection_forms(id) ON DELETE CASCADE;
ALTER TABLE inspection_form_media ADD CONSTRAINT inspection_form_media_diary_media_id_fkey FOREIGN KEY (diary_media_id) REFERENCES diary_media(id) ON DELETE CASCADE;
ALTER TABLE inspection_form_media ADD CONSTRAINT inspection_form_media_form_id_fkey FOREIGN KEY (form_id) REFERENCES inspection_forms(id) ON DELETE CASCADE;
ALTER TABLE inspection_form_media ADD CONSTRAINT inspection_form_media_item_id_fkey FOREIGN KEY (item_id) REFERENCES inspection_form_items(id) ON DELETE CASCADE;
ALTER TABLE inspection_forms ADD CONSTRAINT inspection_forms_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE inspection_forms ADD CONSTRAINT inspection_forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE inspection_forms ADD CONSTRAINT inspection_forms_diary_entry_id_fkey FOREIGN KEY (diary_entry_id) REFERENCES site_diary(id) ON DELETE CASCADE;
ALTER TABLE inspection_forms ADD CONSTRAINT inspection_forms_diary_note_id_fkey FOREIGN KEY (diary_note_id) REFERENCES diary_notes(id) ON DELETE CASCADE;
ALTER TABLE inspection_forms ADD CONSTRAINT inspection_forms_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE job_assignments ADD CONSTRAINT job_assignments_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE job_assignments ADD CONSTRAINT job_assignments_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_auto_uploads ADD CONSTRAINT job_dropbox_auto_uploads_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_auto_uploads ADD CONSTRAINT job_dropbox_auto_uploads_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES job_dropbox_folders(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_auto_uploads ADD CONSTRAINT job_dropbox_auto_uploads_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_folders ADD CONSTRAINT job_dropbox_folders_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_folders ADD CONSTRAINT job_dropbox_folders_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_uploads ADD CONSTRAINT job_dropbox_uploads_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_uploads ADD CONSTRAINT job_dropbox_uploads_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES job_dropbox_folders(id) ON DELETE CASCADE;
ALTER TABLE job_dropbox_uploads ADD CONSTRAINT job_dropbox_uploads_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE job_media ADD CONSTRAINT job_media_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE job_media ADD CONSTRAINT job_media_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE job_tasks ADD CONSTRAINT job_tasks_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE jobs ADD CONSTRAINT jobs_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE jobs ADD CONSTRAINT jobs_manager_id_users_id_fk FOREIGN KEY (manager_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE jobs ADD CONSTRAINT jobs_supervisor_id_users_id_fk FOREIGN KEY (supervisor_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE password_reset_tokens ADD CONSTRAINT password_reset_tokens_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE progress ADD CONSTRAINT progress_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE push_subscriptions ADD CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE scheduler_allocations ADD CONSTRAINT scheduler_allocations_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE scheduler_allocations ADD CONSTRAINT scheduler_allocations_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE scheduler_allocations ADD CONSTRAINT scheduler_allocations_maintenance_job_id_fkey FOREIGN KEY (maintenance_job_id) REFERENCES scheduler_maintenance_jobs(id) ON DELETE CASCADE;
ALTER TABLE scheduler_allocations ADD CONSTRAINT scheduler_allocations_worker_id_scheduler_workers_id_fk FOREIGN KEY (worker_id) REFERENCES scheduler_workers(id) ON DELETE CASCADE;
ALTER TABLE scheduler_job_day_notes ADD CONSTRAINT scheduler_job_day_notes_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE scheduler_job_day_notes ADD CONSTRAINT scheduler_job_day_notes_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE scheduler_maintenance_jobs ADD CONSTRAINT scheduler_maintenance_jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE scheduler_worker_absences ADD CONSTRAINT scheduler_worker_absences_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE scheduler_worker_absences ADD CONSTRAINT scheduler_worker_absences_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES scheduler_workers(id) ON DELETE CASCADE;
ALTER TABLE scheduler_workers ADD CONSTRAINT scheduler_workers_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE site_diary ADD CONSTRAINT site_diary_action_raised_by_users_id_fk FOREIGN KEY (action_raised_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE site_diary ADD CONSTRAINT site_diary_author_id_users_id_fk FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE site_diary ADD CONSTRAINT site_diary_job_id_jobs_id_fk FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE;
ALTER TABLE user_notification_prefs ADD CONSTRAINT user_notification_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT users_company_id_companies_id_fk FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
ALTER TABLE weather_snapshots ADD CONSTRAINT weather_snapshots_diary_entry_id_site_diary_id_fk FOREIGN KEY (diary_entry_id) REFERENCES site_diary(id) ON DELETE CASCADE;


-- ==========================================================================
-- Trigger functions. These are live business logic, not scaffolding --
-- see docs/contract/domain-rules.md R12.
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.enforce_scheduler_worker_absence_no_overlap()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
      BEGIN
        PERFORM pg_advisory_xact_lock(NEW.company_id, NEW.worker_id);
        IF EXISTS (
          SELECT 1
          FROM scheduler_worker_absences existing
          WHERE existing.company_id = NEW.company_id
            AND existing.worker_id = NEW.worker_id
            AND existing.id <> COALESCE(NEW.id, 0)
            AND daterange(existing.start_date, existing.end_date, '[]')
              && daterange(NEW.start_date, NEW.end_date, '[]')
        ) THEN
          RAISE EXCEPTION 'Worker absence periods cannot overlap'
            USING ERRCODE = '23P01';
        END IF;
        RETURN NEW;
      END;
      $function$;

-- ==========================================================================
-- Triggers
-- ==========================================================================

CREATE TRIGGER scheduler_worker_absences_no_overlap_trigger BEFORE INSERT OR UPDATE OF company_id, worker_id, start_date, end_date ON public.scheduler_worker_absences FOR EACH ROW EXECUTE FUNCTION enforce_scheduler_worker_absence_no_overlap();

