[package]
name = "pmk-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
rust_decimal.workspace = true
